### ISSUE TITLE
反馈一下  同样出现问题 无法正常使用

### ISSUE THREAD

**Issue by WindsCloudy** [miyouzi/bilibili_organizer#2]
这是很久以前的下载格式为MP4无分段视频的整理会出现这样的错误

![qq 20170716142629](https://user-images.githubusercontent.com/17917415/28245162-d857217e-6a32-11e7-99bb-d22e12796411.png)

**Comment by WindsCloudy** [comment]
![qq 20170716142430](https://user-images.githubusercontent.com/17917415/28245151-a6b5451a-6a32-11e7-8cb9-ae7a98955259.png)

**Comment by miyouzi** [comment]
能截图下你整理的文件夹吗？（整理工具所在文件夹）

**Comment by WindsCloudy** [comment]
这是最近下载的是blv有分段的视频整理 会出现这样的错误 
两个文件夹除了视频均没有其他的乱七八糟的文件夹 
![qq 20170716142847](https://user-images.githubusercontent.com/17917415/28245172-1c944ef2-6a33-11e7-8c85-0bb8e5954378.png)

**Comment by WindsCloudy** [comment]
我在第一个消息里补充了

**Comment by miyouzi** [comment]
这个工具是要和以av号命名的文件夹放在同一级，而不是放在av号命名的文件夹里，确认下。

**Comment by WindsCloudy** [comment]
。。。。。  我再试试

**Comment by WindsCloudy** [comment]
![qq 20170716143340](https://user-images.githubusercontent.com/17917415/28245196-c7eb8536-6a33-11e7-9cc4-a835a81815a9.png)
好了 QAQ
谢谢快速的回复  真是吓到我了
