### ISSUE TITLE
关于UWP版b站缓存

### ISSUE THREAD

**Issue by walkm-an** [miyouzi/bilibili_organizer#3]
我试了一下b站UWP下载目录的番号，提示会出错..
“merge.ini: no such file or directory”, 我感觉原理是一样的只不过路径格式可能不太一样，所以想问下有没有可能适配UWP版的缓存？
谢谢

**Comment by miyouzi** [comment]
Win下载B站视频推荐 [Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved)

**Comment by walkm-an** [comment]
其实是，我自己缓存了很多视频...只不过文件夹全是av号...我在看网上有没有类似写好脚本可以把av号转成title... 谢谢回复
